{
  pkgs,
  lib,
  config,
  ...
}:

let
  service = "joplin";
  joplin_port = 22300;
  joplin_subdomain = service;
  joplin_uri = "${joplin_subdomain}.${config.modules.services.reverse-proxy.domain}";
  joplin_uid = 1001;
  joplin_gid = 1001;
  joplin_data_dir = "${cfg.volumeDir}/joplin/data";
  postgres_uid = 70;
  postgres_gid = 70;
  postgres_data_dir = "${cfg.volumeDir}/postgres/data";
  cfg = config.modules.services.${service};
in
{
  options.modules.services.${service} = {
    enable = lib.mkEnableOption "Whether to enable custom ${service} settings.";

    volumeDir = lib.mkOption {
      type = lib.types.path;
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.volumeDir} 0755 ${config.modules.base.userName} ${config.modules.base.userName} - -"
      "d ${joplin_data_dir} 0755 ${toString joplin_uid} ${toString joplin_gid} - -"
      "d ${postgres_data_dir} 0755 ${toString postgres_uid} ${toString postgres_gid} - -"
    ];

    sops.secrets."joplin/env" = { };

    services.${config.modules.services.reverse-proxy.service} = {
      virtualHosts."${joplin_uri}".extraConfig = ''
        reverse_proxy localhost:${toString joplin_port}
      '';
    };

    modules.services.dyndns-ovh.subdomains = [ joplin_subdomain ];

    # Containers
    virtualisation.oci-containers.containers."joplin-joplin" = {
      image = "docker.io/joplin/server:latest";
      environment = {
        "APP_BASE_URL" = "https://${joplin_uri}";
        "APP_PORT" = "22300";
        "DB_CLIENT" = "pg";
        "POSTGRES_DATABASE" = "joplin";
        "POSTGRES_HOST" = "joplin-postgres";
        "POSTGRES_PORT" = "5432";
        "STORAGE_DRIVER" = "Type=Filesystem; Path=/data";
      };
      environmentFiles = [
        config.sops.secrets."joplin/env".path
      ];
      volumes = [
        "${joplin_data_dir}:/data:rw"
      ];
      ports = [
        "${toString joplin_port}:22300/tcp"
      ];
      labels = {
        "compose2nix.settings.sops.secrets" = "joplin/env";
        "io.containers.autoupdate" = "registry";
      };
      dependsOn = [
        "joplin-postgres"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=joplin"
        "--network=joplin"
      ];
    };
    systemd.services."podman-joplin-joplin" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-joplin.service"
      ];
      requires = [
        "podman-network-joplin.service"
      ];
      partOf = [
        "podman-compose-joplin-root.target"
      ];
      wantedBy = [
        "podman-compose-joplin-root.target"
      ];
    };
    virtualisation.oci-containers.containers."joplin-postgres" = {
      image = "docker.io/library/postgres:16-alpine";
      environment = {
        "POSTGRES_DB" = "joplin";
      };
      environmentFiles = [
        config.sops.secrets."joplin/env".path
      ];
      volumes = [
        "${postgres_data_dir}:/var/lib/postgresql/data:rw"
      ];
      labels = {
        "compose2nix.settings.sops.secrets" = "joplin/env";
        "io.containers.autoupdate" = "registry";
      };
      log-driver = "journald";
      extraOptions = [
        "--network-alias=postgres"
        "--network=joplin"
      ];
    };
    systemd.services."podman-joplin-postgres" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-joplin.service"
      ];
      requires = [
        "podman-network-joplin.service"
      ];
      partOf = [
        "podman-compose-joplin-root.target"
      ];
      wantedBy = [
        "podman-compose-joplin-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-joplin" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f joplin";
      };
      script = ''
        podman network inspect joplin || podman network create joplin
      '';
      partOf = [ "podman-compose-joplin-root.target" ];
      wantedBy = [ "podman-compose-joplin-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-joplin-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
