{
  pkgs,
  lib,
  config,
  ...
}:

let
  service = "joplin";
  port = 22300;
  uri = "${service}.${config.modules.services.reverse-proxy.domain}";
  joplin_uid = 1001;
  joplin_gid = 1001;
  joplin_data_volume = "${cfg.volumeDir}/data";
  postgres_uid = 70;
  postgres_gid = 70;
  postgres_data_volume = "${cfg.volumeDir}/postgresql/data";
  uid = config.users.users.${config.modules.base.userName}.uid;
  gid = config.users.groups.${config.modules.base.userName}.gid;
  cfg = config.modules.services.${service};
in
{
  options.modules.services.${service} = {
    enable = lib.mkEnableOption "Whether to enable custom ${service} settings.";

    volumeDir = lib.mkOption {
      type = lib.types.path;
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.volumeDir} 0755 ${toString uid} ${toString gid} - -"
      "d ${joplin_data_volume} 0755 ${toString joplin_uid} ${toString joplin_gid} - -"
      "d ${postgres_data_volume} 0755 ${toString postgres_uid} ${toString postgres_gid} - -"
    ];

    sops.secrets."joplin/env" = { };

    services.${config.modules.services.reverse-proxy.service} = {
      virtualHosts."${uri}".extraConfig = ''
        reverse_proxy localhost:${toString port}
      '';
    };

    modules.services.dyndns-ovh.subdomains = [ service ];

    # Containers
    virtualisation.oci-containers.containers."joplin" = {
      image = "docker.io/joplin/server:latest";
      environment = {
        "APP_BASE_URL" = "https://${uri}";
        "APP_PORT" = "22300";
        "DB_CLIENT" = "pg";
        "POSTGRES_DATABASE" = "joplin";
        "POSTGRES_HOST" = "joplin-postgres";
        "POSTGRES_PORT" = "5432";
        "STORAGE_DRIVER" = "Type=Filesystem; Path=/data";
      };
      environmentFiles = [
        config.sops.secrets."joplin/env".path
      ];
      volumes = [
        "${joplin_data_volume}:/data:rw"
      ];
      ports = [
        "${toString port}:22300/tcp"
      ];
      labels = {
        "compose2nix.settings.sops.secrets" = "joplin/env";
        "io.containers.autoupdate" = "registry";
      };
      dependsOn = [
        "joplin-postgres"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=joplin"
        "--network=joplin"
      ];
    };
    systemd.services."podman-joplin" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-joplin.service"
      ];
      requires = [
        "podman-network-joplin.service"
      ];
      partOf = [
        "podman-compose-joplin-root.target"
      ];
      wantedBy = [
        "podman-compose-joplin-root.target"
      ];
    };
    virtualisation.oci-containers.containers."joplin-postgres" = {
      image = "docker.io/library/postgres:16-alpine";
      environment = {
        "POSTGRES_DB" = "joplin";
      };
      environmentFiles = [
        config.sops.secrets."joplin/env".path
      ];
      volumes = [
        "${postgres_data_volume}:/var/lib/postgresql/data:rw"
      ];
      labels = {
        "compose2nix.settings.sops.secrets" = "joplin/env";
        "io.containers.autoupdate" = "registry";
      };
      log-driver = "journald";
      extraOptions = [
        "--network-alias=joplin-postgres"
        "--network=joplin"
      ];
    };
    systemd.services."podman-joplin-postgres" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-joplin.service"
      ];
      requires = [
        "podman-network-joplin.service"
      ];
      partOf = [
        "podman-compose-joplin-root.target"
      ];
      wantedBy = [
        "podman-compose-joplin-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-joplin" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f joplin";
      };
      script = ''
        podman network inspect joplin || podman network create joplin
      '';
      partOf = [ "podman-compose-joplin-root.target" ];
      wantedBy = [ "podman-compose-joplin-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-joplin-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
