{
  pkgs,
  lib,
  config,
  ...
}:

let
  service = "vaultwarden";
  port = 8000;
  subdomain = service;
  uri = "${subdomain}.${config.modules.services.reverse-proxy.domain}";
  uid = 0;
  gid = 0;
  data_dir = "${cfg.volumeDir}/data";
  cfg = config.modules.services.${service};
in
{
  options.modules.services.${service} = {
    enable = lib.mkEnableOption "Whether to enable custom ${service} settings.";

    volumeDir = lib.mkOption {
      type = lib.types.path;
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.volumeDir} 0755 ${config.modules.base.userName} ${config.modules.base.groupName} - -"
      "d ${data_dir} 0755 ${toString uid} ${toString gid} - -"
    ];

    sops.secrets."vaultwarden/env" = { };

    services.${config.modules.services.reverse-proxy.service} = {
      virtualHosts."${uri}".extraConfig = ''
          reverse_proxy localhost:${toString port}{
          header_up X-Real-IP {remote_host}
        }
      '';
    };

    modules.services.dyndns-ovh.subdomains = [ subdomain ];

    # Containers
    virtualisation.oci-containers.containers."vaultwarden" = {
      image = "docker.io/vaultwarden/server:latest";
      environment = {
        "DOMAIN" = "https://${uri}";
        "SIGNUPS_ALLOWED" = "false";
        "SMTP_FROM" = "${subdomain}@${config.modules.services.reverse-proxy.domain}";
        "SMTP_FROM_NAME" = "${config.modules.services.reverse-proxy.domain} ${subdomain} server";
        "SMTP_HOST" = config.programs.msmtp.accounts.default.host;
        "SMTP_PORT" = toString config.programs.msmtp.accounts.default.port;
        "SMTP_SECURITY" = "starttls";
        "SMTP_USERNAME" = config.programs.msmtp.accounts.default.user;
      };
      environmentFiles = [
        config.sops.secrets."vaultwarden/env".path
      ];
      volumes = [
        "${data_dir}:/data:rw"
      ];
      ports = [
        "${toString port}:80/tcp"
      ];
      labels = {
        "compose2nix.settings.sops.secrets" = "vaultwarden/env";
        "io.containers.autoupdate" = "registry";
      };
      log-driver = "journald";
      extraOptions = [
        "--network-alias=vaultwarden"
        "--network=vaultwarden"
      ];
    };
    systemd.services."podman-vaultwarden" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-vaultwarden.service"
      ];
      requires = [
        "podman-network-vaultwarden.service"
      ];
      partOf = [
        "podman-compose-vaultwarden-root.target"
      ];
      wantedBy = [
        "podman-compose-vaultwarden-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-vaultwarden" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f vaultwarden";
      };
      script = ''
        podman network inspect vaultwarden || podman network create vaultwarden
      '';
      partOf = [ "podman-compose-vaultwarden-root.target" ];
      wantedBy = [ "podman-compose-vaultwarden-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-vaultwarden-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
