# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  config,
  ...
}:

let
  service = "clonarr";
  port = 6060;
  clonarr_config_volume = "${cfg.volumeDir}/config";
  clonarr_uid = config.modules.base.uid;
  clonarr_gid = config.modules.base.gid;
  cfg = config.modules.services.media-server.${service};
in
{
  options.modules.services.media-server.${service} = {
    enable = lib.mkEnableOption "Whether to enable custom ${service} settings.";

    volumeDir = lib.mkOption {
      type = lib.types.path;
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.volumeDir} 0755 ${config.modules.base.userName} ${config.modules.base.groupName} - -"
      "d ${clonarr_config_volume} 0755 ${toString clonarr_uid} ${toString clonarr_gid} - -"
    ];

    networking.firewall.allowedTCPPorts = [
      port
    ];

    # Containers
    virtualisation.oci-containers.containers."clonarr" = {
      image = "ghcr.io/prophetse7en/clonarr:latest";
      environment = {
        "PGID" = toString clonarr_gid;
        "PUID" = toString clonarr_uid;
        "TZ" = "Europe/Paris";
      };
      volumes = [
        "${clonarr_config_volume}:/config:rw"
      ];
      ports = [
        "${toString port}:6060/tcp"
      ];
      labels = {
        "io.containers.autoupdate" = "registry";
      };
      log-driver = "journald";
      extraOptions = [
        "--network-alias=clonarr"
        "--network=clonarr"
      ];
    };
    systemd.services."podman-clonarr" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-clonarr.service"
      ];
      requires = [
        "podman-network-clonarr.service"
      ];
      partOf = [
        "podman-compose-clonarr-root.target"
      ];
      wantedBy = [
        "podman-compose-clonarr-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-clonarr" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f clonarr";
      };
      script = ''
        podman network inspect clonarr || podman network create clonarr
      '';
      partOf = [ "podman-compose-clonarr-root.target" ];
      wantedBy = [ "podman-compose-clonarr-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-clonarr-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
