# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  config,
  ...
}:

let
  service = "clonarr";
  port = 6060;
  uid = "99";
  gid = "100";
  cfg = config.modules.services.media-server.${service};
in
{
  options.modules.services.media-server.${service} = {
    enable = lib.mkEnableOption "Whether to enable custom ${service} settings.";

    volumeDir = lib.mkOption {
      type = lib.types.path;
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.volumeDir}/config 0755 ${uid} ${gid} - -"
    ];

    networking.firewall.allowedTCPPorts = [
      port
    ];

    # Containers
    virtualisation.oci-containers.containers."clonarr" = {
      image = "ghcr.io/prophetse7en/clonarr:latest";
      environment = {
        "PGID" = gid;
        "PUID" = uid;
        "TZ" = "Europe/Paris";
      };
      volumes = [
        "${cfg.volumeDir}/config:/config:rw"
      ];
      ports = [
        "${toString port}:6060/tcp"
      ];
      labels = {
        "io.containers.autoupdate" = "registry";
      };
      log-driver = "journald";
      extraOptions = [
        "--network-alias=clonarr"
        "--network=clonarr"
      ];
    };
    systemd.services."podman-clonarr" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-clonarr.service"
      ];
      requires = [
        "podman-network-clonarr.service"
      ];
      partOf = [
        "podman-compose-clonarr-root.target"
      ];
      wantedBy = [
        "podman-compose-clonarr-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-clonarr" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f clonarr";
      };
      script = ''
        podman network inspect clonarr || podman network create clonarr
      '';
      partOf = [ "podman-compose-clonarr-root.target" ];
      wantedBy = [ "podman-compose-clonarr-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-clonarr-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
