name: &name clonarr

services:
  clonarr:
    container_name: *name
    image: ghcr.io/prophetse7en/clonarr:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/external/data-vault/services/media-server/clonarr/config:/config
    ports:
      - 6060:6060
    labels:
      - io.containers.autoupdate=registry

networks:
  default:
    name: *name

# nix run nixpkgs#compose2nix -- -write_nix_setup=false -enable_option -inputs modules/services/media-server/clonarr/docker-compose.yml -output modules/services/media-server/clonarr/default-debug.nix
