# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  config,
  ...
}:

let
  service = "qui";
  port = 7476;
  cfg = config.modules.services.media-server.${service};
in
{
  options.modules.services.media-server.${service} = {
    enable = lib.mkEnableOption "Whether to enable custom ${service} settings.";

    volumeDir = lib.mkOption {
      type = lib.types.path;
    };

    qbittorrentSavePath = lib.mkOption {
      type = lib.types.path;
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.volumeDir}/config 0755 root root - -"
    ];

    networking.firewall.allowedTCPPorts = [
      port
    ];

    # Containers
    virtualisation.oci-containers.containers.${service} = {
      image = "ghcr.io/autobrr/qui:latest";
      volumes = [
        "${cfg.volumeDir}/config:/config:rw"
        "${cfg.qbittorrentSavePath}:${cfg.qbittorrentSavePath}:rw"
      ];
      ports = [
        "${toString port}:7476/tcp"
      ];
      labels = {
        "io.containers.autoupdate" = "registry";
      };
      log-driver = "journald";
      extraOptions = [
        "--network-alias=qui"
        "--network=qui"
      ];
    };
    systemd.services."podman-qui" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-qui.service"
      ];
      requires = [
        "podman-network-qui.service"
      ];
      partOf = [
        "podman-compose-qui-root.target"
      ];
      wantedBy = [
        "podman-compose-qui-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-qui" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f qui";
      };
      script = ''
        podman network inspect qui || podman network create qui
      '';
      partOf = [ "podman-compose-qui-root.target" ];
      wantedBy = [ "podman-compose-qui-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-qui-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
