# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  config,
  ...
}:

let
  service = "ygege";
  cfg = config.modules.services.media-server.${service};
in
{
  options.modules.services.media-server.${service} = {
    enable = lib.mkEnableOption "Whether to enable custom ${service} settings.";
  };

  config = lib.mkIf cfg.enable {
    # Containers
    virtualisation.oci-containers.containers."ygege" = {
      image = "uwucode/ygege:latest";
      environment = {
        "LOG_LEVEL" = "info";
      };
      ports = [
        "8715:8715/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--health-cmd=curl --fail http://localhost:\${BIND_PORT:-8715}/health || exit 1"
        "--health-interval=1m30s"
        "--health-retries=3"
        "--health-start-period=10s"
        "--health-timeout=20s"
        "--network-alias=ygege"
        "--network=ygege"
      ];
    };
    systemd.services."podman-ygege" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-ygege.service"
      ];
      requires = [
        "podman-network-ygege.service"
      ];
      partOf = [
        "podman-compose-ygege-root.target"
      ];
      wantedBy = [
        "podman-compose-ygege-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-ygege" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f ygege";
      };
      script = ''
        podman network inspect ygege || podman network create ygege
      '';
      partOf = [ "podman-compose-ygege-root.target" ];
      wantedBy = [ "podman-compose-ygege-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-ygege-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
