{
  pkgs,
  lib,
  config,
  ...
}:

let
  service = "mealie";
  port = 9000;
  uri = "${service}.${config.modules.services.reverse-proxy.domain}";
  mealie_uid = 911;
  mealie_gid = 911;
  mealie_data_volume = "${cfg.volumeDir}/data";
  cfg = config.modules.services.${service};
in
{
  options.modules.services.${service} = {
    enable = lib.mkEnableOption "Whether to enable custom ${service} settings.";

    volumeDir = lib.mkOption {
      type = lib.types.path;
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = [
      "d ${cfg.volumeDir} 0755 ${config.modules.base.userName} ${config.modules.base.groupName} - -"
      "d ${mealie_data_volume} 0755 ${toString mealie_uid} ${toString mealie_gid} - -"
    ];

    services.${config.modules.services.reverse-proxy.service} = {
      virtualHosts."${uri}".extraConfig = ''
        reverse_proxy localhost:${toString port}
      '';
    };

    modules.services.dyndns-ovh.subdomains = [ service ];

    # Containers
    virtualisation.oci-containers.containers."mealie" = {
      image = "ghcr.io/mealie-recipes/mealie:latest";
      environment = {
        "BASE_URL" = "https://${uri}";
        "PGID" = toString mealie_gid;
        "PUID" = toString mealie_uid;
        "TZ" = config.time.timeZone;
      };
      volumes = [
        "${mealie_data_volume}:/app/data:rw"
      ];
      ports = [
        "${toString port}:9000/tcp"
      ];
      labels = {
        "io.containers.autoupdate" = "registry";
      };
      log-driver = "journald";
      extraOptions = [
        "--network-alias=mealie"
        "--network=mealie"
      ];
    };
    systemd.services."podman-mealie" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-mealie.service"
      ];
      requires = [
        "podman-network-mealie.service"
      ];
      partOf = [
        "podman-compose-mealie-root.target"
      ];
      wantedBy = [
        "podman-compose-mealie-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-mealie" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f mealie";
      };
      script = ''
        podman network inspect mealie || podman network create mealie
      '';
      partOf = [ "podman-compose-mealie-root.target" ];
      wantedBy = [ "podman-compose-mealie-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-mealie-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
