{
  pkgs,
  lib,
  config,
  ...
}:

let
  media_dir = "${cfg.volumeDir}/media";
  torrents_dir = "${cfg.volumeDir}/torrents";
  uid = config.modules.base.uid;
  gid = config.modules.base.gid;
  timezone = config.modules.base.timeZone;
  clonarr_port = 6060;
  clonarr_volume_dir = "${cfg.volumeDir}/clonarr";
  clonarr_config_dir = "${clonarr_volume_dir}/config";
  utils = import ../../../utils;
  cfg = config.modules.services.media-server;
in
{
  imports = utils.importSubmodules { dir = ./.; };

  options.modules.services.media-server = {
    enable = lib.mkEnableOption "Whether to enable custom media server settings.";

    volumeDir = lib.mkOption {
      type = lib.types.path;
    };

    subnetWhitelist = lib.mkOption {
      type = lib.types.str;
    };

    torrentingPort = lib.mkOption {
      type = lib.types.int;
    };
  };

  config = lib.mkIf cfg.enable {
    modules.services.media-server = {
      bazarr.enable = true;
      cross-seed.enable = true;
      filebrowser = {
        enable = true;
        rootDir = "${media_dir}";
      };
      flaresolverr.enable = true;
      jellyfin.enable = true;
      prowlarr.enable = true;
      radarr.enable = true;
      seerr.enable = true;
      sonarr.enable = true;
      torrent-downloader = {
        enable = true;
        savePath = "${torrents_dir}";
        subnetWhitelist = cfg.subnetWhitelist;
        torrentingPort = cfg.torrentingPort;
      };
      wireguard-netns.enable = true;
    };

    systemd.tmpfiles.rules = [
      "d ${cfg.volumeDir} 0755 ${toString uid} ${toString gid} - -"
      "d ${media_dir} 0755 ${toString uid} ${toString gid} - -"
      "d ${torrents_dir} 0755 ${toString uid} ${toString gid} - -"
      "d ${clonarr_volume_dir} 0755 ${toString uid} ${toString gid} - -"
      "d ${clonarr_config_dir} 0755 ${toString uid} ${toString gid} - -"
    ];

    networking.firewall.allowedTCPPorts = [ clonarr_port ];

    # Containers
    virtualisation.oci-containers.containers."media-server-clonarr" = {
      image = "ghcr.io/prophetse7en/clonarr:latest";
      environment = {
        "PGID" = toString gid;
        "PUID" = toString uid;
        "TZ" = timezone;
      };
      volumes = [
        "${clonarr_config_dir}:/config:rw"
      ];
      ports = [
        "${toString clonarr_port}:6060/tcp"
      ];
      labels = {
        "io.containers.autoupdate" = "registry";
      };
      log-driver = "journald";
      extraOptions = [
        "--network-alias=clonarr"
        "--network=media-server"
      ];
    };
    systemd.services."podman-media-server-clonarr" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-media-server.service"
      ];
      requires = [
        "podman-network-media-server.service"
      ];
      partOf = [
        "podman-compose-media-server-root.target"
      ];
      wantedBy = [
        "podman-compose-media-server-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-media-server" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f media-server";
      };
      script = ''
        podman network inspect media-server || podman network create media-server
      '';
      partOf = [ "podman-compose-media-server-root.target" ];
      wantedBy = [ "podman-compose-media-server-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-media-server-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
