x-restart: &restart unless-stopped
x-pull_policy: &pull_policy always
x-puid: &puid PUID=1000
x-pgid: &pgid PGID=1000
x-tz: &tz TZ=Europe/Paris
x-data: &data "/media/external/data-vault/services/media-server:/data"
x-media: &media "/media/external/data-vault/services/media-server/media:/data/media"
x-torrents: &torrents "/media/external/data-vault/services/media-server/torrents:/data/torrents"

name: &name media-server

services:
  bazarr:
    container_name: media-server-bazarr
    image: lscr.io/linuxserver/bazarr:latest
    pull_policy: *pull_policy
    restart: *restart
    ports:
      - 6767:6767
    environment:
      - *puid
      - *pgid
      - *tz
    volumes:
      - *media
      - /media/external/data-vault/services/media-server/bazarr/config:/config
    labels:
      - io.containers.autoupdate=registry

  clonarr:
    container_name: media-server-clonarr
    image: ghcr.io/prophetse7en/clonarr:latest
    pull_policy: *pull_policy
    restart: *restart
    ports:
      - 6060:6060
    environment:
      - *puid
      - *pgid
      - *tz
    volumes:
      - /media/external/data-vault/services/media-server/clonarr/config:/config
    labels:
      - io.containers.autoupdate=registry

  gluetun:
    image: docker.io/qmcgaw/gluetun:v3
    container_name: media-server-gluetun
    pull_policy: *pull_policy
    restart: *restart
    environment:
      - *puid
      - *pgid
      - *tz
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - SERVER_COUNTRIES=Netherlands
      - FIREWALL_VPN_INPUT_PORTS=47563
      - UPDATER_PERIOD=480h
    ports:
      - 8080:8080 # qBittorrent webui
    volumes:
      - /media/external/data-vault/services/media-server/gluetun/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    labels:
      - compose2nix.settings.sops.secrets=media-server/gluetun/env
      - io.containers.autoupdate=registry

  prowlarr:
    container_name: media-server-prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    pull_policy: *pull_policy
    restart: *restart
    ports:
      - 9696:9696
    environment:
      - *puid
      - *pgid
      - *tz
    volumes:
      - /media/external/data-vault/services/media-server/prowlarr/config:/config
    labels:
      - io.containers.autoupdate=registry

  qbittorrent:
    container_name: media-server-qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: *pull_policy
    restart: *restart
    environment:
      - *puid
      - *pgid
      - *tz
      - WEBUI_PORT=8080
      - TORRENTING_PORT=47563
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - *torrents
      - /media/external/data-vault/services/media-server/qbittorrent/config:/config
    labels:
      - io.containers.autoupdate=registry
    network_mode: "service:gluetun"

  radarr:
    container_name: media-server-radarr
    image: lscr.io/linuxserver/radarr:latest
    pull_policy: *pull_policy
    restart: *restart
    ports:
      - 7878:7878
    environment:
      - *puid
      - *pgid
      - *tz
    volumes:
      - *data
      - /media/external/data-vault/services/media-server/radarr/config:/config
    labels:
      - io.containers.autoupdate=registry

  seerr:
    container_name: media-server-seerr
    image: docker.io/seerr/seerr:latest
    pull_policy: *pull_policy
    restart: *restart
    ports:
      - 5055:5055
    environment:
      - *tz
    volumes:
      - /media/external/data-vault/services/media-server/seerr/config:/app/config
    labels:
      - io.containers.autoupdate=registry
    init: true

  sonarr:
    container_name: media-server-sonarr
    image: lscr.io/linuxserver/sonarr:latest
    pull_policy: *pull_policy
    restart: *restart
    ports:
      - 8989:8989
    environment:
      - *puid
      - *pgid
      - *tz
    volumes:
      - *data
      - /media/external/data-vault/services/media-server/sonarr/config:/config
    labels:
      - io.containers.autoupdate=registry

networks:
  default:
    name: *name

# sudo nix run nixpkgs#compose2nix -- -auto_format -write_nix_setup=false -enable_option -inputs modules/services/media-server/docker-compose.yml -output modules/services/media-server/default-debug.nix --sops_file /etc/nixos/secrets/default.yaml && sudo chown gsegt:gsegt modules/services/media-server/default-debug.nix
