{
  pkgs,
  lib,
  config,
  ...
}:

let
  service = "radicale";
  port = 5232;
  subdomain = service;
  uri = "${subdomain}.${config.modules.services.reverse-proxy.domain}";
  uid = 1000;
  gid = 1000;
  data_dir = "${cfg.volumeDir}/data";
  ref_dir = "/etc/nixos/modules/services/${service}";
  cfg = config.modules.services.${service};
in
{
  options.modules.services.${service} = {
    enable = lib.mkEnableOption "Whether to enable custom ${service} settings.";

    volumeDir = lib.mkOption {
      type = lib.types.path;
    };
  };

  config = lib.mkIf cfg.enable {
    sops.secrets."radicale/htpasswd" = {
      uid = uid;
      gid = gid;
    };

    systemd.tmpfiles.rules = [
      "d ${cfg.volumeDir} 0755 ${config.modules.base.userName} ${config.modules.base.groupName} - -"
      "d ${data_dir} 0755 ${toString uid} ${toString gid} - -"
    ];

    services.${config.modules.services.reverse-proxy.service} = {
      virtualHosts."${uri}".extraConfig = ''
          reverse_proxy localhost:${toString port}{
          header_up Host {host}
          header_up X-Forwarded-Port {port}
          header_up X-Remote-User {http.auth.user.id}
        }
      '';
    };

    modules.services.dyndns-ovh.subdomains = [ subdomain ];

    # Containers
    virtualisation.oci-containers.containers."radicale" = {
      image = "docker.io/kozea/radicale:latest";
      volumes = [
        "${ref_dir}/config:/etc/radicale/config:ro"
        "${data_dir}:/var/lib/radicale:rw"
        "${config.sops.secrets."radicale/htpasswd".path}:${config.sops.secrets."radicale/htpasswd".path}:ro"
      ];
      ports = [
        "${toString port}:5232/tcp"
      ];
      labels = {
        "io.containers.autoupdate" = "registry";
      };
      log-driver = "journald";
      extraOptions = [
        "--network-alias=radicale"
        "--network=radicale"
      ];
    };
    systemd.services."podman-radicale" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-radicale.service"
      ];
      requires = [
        "podman-network-radicale.service"
      ];
      partOf = [
        "podman-compose-radicale-root.target"
      ];
      wantedBy = [
        "podman-compose-radicale-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-radicale" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f radicale";
      };
      script = ''
        podman network inspect radicale || podman network create radicale
      '';
      partOf = [ "podman-compose-radicale-root.target" ];
      wantedBy = [ "podman-compose-radicale-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-radicale-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
