user: ENC[AES256_GCM,data:ZXlR+0odvX6JI0UoEI2KEdC+L6eftDuDQg4Erc6x8xIRZ4iKhU2tZziNXQ1w4c1ouAn8fZ0p1/LRULoP+/62UV6opaDPF2laaA==,iv:syv7HqxZaQrnj5TF56fKS18trR71wdF02mkY9A9dBqs=,tag:1CHjoy8bv3fv9sz8hxlBsg==,type:str]
vpn:
    ipv4: ENC[AES256_GCM,data:besv6wIM0OJJcnZPWyuMsac=,iv:jE6Eq3zwbFHWVAw2WRk3jo1upMIv0+4cAMBGVHQtDug=,tag:KVJnQxulLfmL7o69jJXcdQ==,type:str]
    wg.conf: ENC[AES256_GCM,data:lwfM9KN4fb8pAURqbk7zZchocXCj+vbNNuqSRIcIFOM1pHsfloaY10Uj7kkHurDJ3tzFhmXvji2mpl9WIx8hE+v10MnDnHY0f5GLtOiZZoujQh5rMLfHBR1iHRFQsg+JeEQbFsANn7FvkmlutOtr97klQfBtju2gtUDV+ataVFKkLSuLcom3WaU7PyL2KJf/E5JEXrmP9c1IghjVETSzmn4b0ptHjXtIMBm17QfXEqgXk4oYNwPUGqWzvSTgP5Y4+yy+NoORcM8Bh+9E9bFDWyL6Fxk/QHFycgIYi9ktlf7HROPJGzUgdskr48CqU3pn/rrt0gwHkbK37NpxYjk9,iv:iHy+3N0i7I9GJwYASoq04NH86l6+9DbwgQTGA+HhHXY=,tag:+DicO3cGLPsa4lON7chllQ==,type:str]
dyndns-ovh:
    login: ENC[AES256_GCM,data:LCMEmXMT2cUfKSME,iv:GW0qoRkzar35kB/XuenW8MdDPzXVu448AYdnIpEGDNU=,tag:JkzdEBOuEE213AEuf8O/BA==,type:str]
    password: ENC[AES256_GCM,data:rUZG9InbXwJhVjwetXH+PjCd+YFT4L7qcR1y7eVDdg==,iv:j/Rk0y/onogzX4a/7UbjuiJY8Sx3PjxJZhDxC40uBR8=,tag:8b9pl1EyTB8J69h2NEqASQ==,type:str]
radicale:
    htpasswd: ENC[AES256_GCM,data:7TWKFq+GpaU7lLSh+2cBC+wALAIDa/wxzoX/EMdS+lQtV8qlALHB,iv:xIr5PRqya06ukxyUDhzEcx4V0UWTvBtDmnUmZdyXisI=,tag:TLQQjw7LKJmXGZjxPDM/ZA==,type:str]
joplin:
    env: ENC[AES256_GCM,data:l29eRN+WoUo5yif+Urzl4QIox9G4RLmDoPJXapcfhL1hbfdP4GERi2kZfxBlhw==,iv:3nQWdHzfRAIoTH5roCDSytkczdZ0CII0mGB9IVxCjTo=,tag:SDlyVk55De2hILV0i0gYmg==,type:str]
msmtp_default_password: ENC[AES256_GCM,data:Sa0jKbq0FjfO9fcc7UwjeN93tgu1lcaPHj+Vo78h,iv:/sWHdJigCDX1arqxFgxFzCLn2zNRj7onqFA792C7YhI=,tag:xx9wMgWw9j6m8pKhWemBXg==,type:str]
opencloud:
    opencloud:
        env: ENC[AES256_GCM,data:itj/cY25aMTZGAHzPTS6GECyvqLT9jpFgMGYBnjFrfz+K9+N3BUfnmcVzhKkjRycq+B5Rw==,iv:0rdh+ByH+72qlfUQv21WXDvfhFcgZLShROirQJi69gk=,tag:EBHRlVfYtFLqpveEg7MHbg==,type:str]
    collabora:
        env: ENC[AES256_GCM,data:QvzIdXkSx6M7yJwNaosN1mO9Iq6m+VYMWThc574CgaOTcDqi8OsSCPn3,iv:Kgb8pz7QY0n9kIzQsCxWyl/cCiX/YoSs6Nxl87HnW04=,tag:a1rnaU/u63ifJyCcwHyNtQ==,type:str]
cross-seed:
    settings.json: ENC[AES256_GCM,data:c7EhcA/AtNdYUR96CirAHfpAb+uQjzOQdfW3MCoQwKZlsaDDWOYPlFd3FwbxDghQJ3SkzOG0qgGHZoMrIngHzvxKUXcypCpAIrmh83XfLdoG6YbwByl2r0SI2v+biCwfK/ouxbIUXknUEnHqJgU0U6k0mbJb2xUo/pXb9nrPCMhP/w6Yx0ZY16TR+PafbsuOAWw9JRK2+aqTlYom9SkHOt1oCSaOzIpuSx37jmpMS41CJQSbSk8pUOLePoIeTo3xXiBAQofLBCquD0i8miIVhkpMZM1PbYoy908JoqyeTiV1jJMHrMsa2CrhNa5MV2f6OA8nHJXzJl/YVujfj7HkYNLM3yD6AI6IVCS1Bg7exjNmHpf62c+RwYwtTKoyhwInHPBXVwmRogg2828nMOSuUphJXJgxdiBpWtSAlZ1kHUwv97J8wOiihkP4KJxKrtd1fB3OAnmrW/al7VK+d1sKG/Op1cobd5cTOMNqnBATQDIWqSD+l4doghOAwCg2kDqIqv0U2fvbX5YKyuUo0iec0N3AvL6qRZnCkPPYKU2KfbgIT1LaNgmf3fL5,iv:/r9iZrwQegRoRyzsOFceHPkq59PzHNDbZXb557JfNXY=,tag:WF2SNrW7bdoS8vMZQBOVjw==,type:str]
vaultwarden:
    env: ENC[AES256_GCM,data:QG3erPX68/rQJM/pJaR1B0gxVDaWqjY8zcCipPw1W7KMHt5zCYKZdmzwX4F9J+NHLa07K2ZXFz/ckB2aXPuDOQd6q/MWUAwX8eufQqoju4Zfn47f9FeddpoCUj3pOG5FmBpiDnFodirz8ICXL4KL+K1IlNPUTV001DeQ7Ox0F2JUwqfbu5xSd7MPe/Bc8a2IuROccRqOZIr8r05X2mbOyw3SJwWDm5uGwK3z4qfcY3tvhsFlrTgEUsZnvPOxXvHUka0=,iv:VjOv0+mVnDcDOp4mtPGfA9Xv8QIBGtxCimcCJ5KoD20=,tag:x5fBBQSzdqa4iSmq4YiLGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc3dYbHllY3A3VE9tY3M0
            L29DZzVZcmhSbHRaNE5obWdzUWtjWU9zYVJjCmQrT09QMkd5YmRtbDcyOGRFbVA0
            UERNWTEzMTlwbC9jU0FvYTB3Vmx6eTgKLS0tIGIyODdwMlMxcXZ1SmF6dlBxNTRi
            d3pNM0s2UlFwaW9wM3k4V1pCOXhTeWsKjT+yx4t4kMEGgMJe+xWtv/YQksc6fN3R
            IEJ2S3aksn9iWQRqnovf+9ez25MGvJMk+gFHmLA35e8QYKPYPxajwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7u3v4csrvqqcxw0u0mgz22qa63ft3sscdl8yan2ge4k7trtacjqy0w7uf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTenYwai9JVUo4RWZqY3dY
            OERnK0lnOW9uUzBHeXpGaE1yL1FRSVJpUWlFCndyYUU0RHZVL1pYV1NRRHZ1RTFI
            c1hzcHlCcmFOYWdFekp0Rm55aXlkcE0KLS0tIEh4SFVjSmpFOHFOQ0d3VGUxU3dX
            ZUxwMVkvR1k2OXp0R3M1TEw0aWdGeTQKvzD3rLsGZAQxE5xc/6lJkawqQ0Lf9gKC
            UX7TA8fNi0mvtHmoEWCURa/GdLbmHXMg7eMq/Y2MpUsYHkM3RL2YqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17ate9csmpldp5596mkfs4lklj9338ahgqd2lxtv757wp8xey75mq9e5gvp
    lastmodified: "2026-06-14T17:41:02Z"
    mac: ENC[AES256_GCM,data:ufcgB5xsTJqwPpWEBd29fkaJRI7Znj19RJdfbAegA+0veQg3yyNSw9/fuBKRXewureXqvZMmk1HRzaoNJWpzKRZ+JvbA/wkj2QjOHWEDhGk6+b6cb3f2JAW3cSAIXRunG3T2B+kSkY7u22FRfOgxVwZ9S7yANo63rzHTXoq1KUg=,iv:sA1QWJAvCAUr4bv1sT1Q89pXpdK5b5vfqwl79wn4Mzg=,tag:SPlbjvA25X5ffg27k55qPA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
