user: ENC[AES256_GCM,data:ZXlR+0odvX6JI0UoEI2KEdC+L6eftDuDQg4Erc6x8xIRZ4iKhU2tZziNXQ1w4c1ouAn8fZ0p1/LRULoP+/62UV6opaDPF2laaA==,iv:syv7HqxZaQrnj5TF56fKS18trR71wdF02mkY9A9dBqs=,tag:1CHjoy8bv3fv9sz8hxlBsg==,type:str]
radarr_api_key: ENC[AES256_GCM,data:jmEyJcyZFp4ENkd+KQOKMZ6JB4FGKjeMFm4zF99ixZQ=,iv:shkeNHAQm9Td3a1CdJtSHrParQjevfh9IH5Z8At2jjE=,tag:pLVMza7Amzs/ZatQj+bJQw==,type:str]
sonarr_api_key: ENC[AES256_GCM,data:roXuOBPgMq5iyGRlMEdruXetC3kXHtby5mVlhtZpURg=,iv:bGU+AMF8c1n75ttRpg6cBVVh31Qff3Nn5kirHAWoiQs=,tag:sq+3zb4I/HAo9MNS7UWrYw==,type:str]
vpn:
    ipv4: ENC[AES256_GCM,data:besv6wIM0OJJcnZPWyuMsac=,iv:jE6Eq3zwbFHWVAw2WRk3jo1upMIv0+4cAMBGVHQtDug=,tag:KVJnQxulLfmL7o69jJXcdQ==,type:str]
    wg.conf: ENC[AES256_GCM,data:lwfM9KN4fb8pAURqbk7zZchocXCj+vbNNuqSRIcIFOM1pHsfloaY10Uj7kkHurDJ3tzFhmXvji2mpl9WIx8hE+v10MnDnHY0f5GLtOiZZoujQh5rMLfHBR1iHRFQsg+JeEQbFsANn7FvkmlutOtr97klQfBtju2gtUDV+ataVFKkLSuLcom3WaU7PyL2KJf/E5JEXrmP9c1IghjVETSzmn4b0ptHjXtIMBm17QfXEqgXk4oYNwPUGqWzvSTgP5Y4+yy+NoORcM8Bh+9E9bFDWyL6Fxk/QHFycgIYi9ktlf7HROPJGzUgdskr48CqU3pn/rrt0gwHkbK37NpxYjk9,iv:iHy+3N0i7I9GJwYASoq04NH86l6+9DbwgQTGA+HhHXY=,tag:+DicO3cGLPsa4lON7chllQ==,type:str]
dyndns-ovh:
    login: ENC[AES256_GCM,data:LCMEmXMT2cUfKSME,iv:GW0qoRkzar35kB/XuenW8MdDPzXVu448AYdnIpEGDNU=,tag:JkzdEBOuEE213AEuf8O/BA==,type:str]
    password: ENC[AES256_GCM,data:rUZG9InbXwJhVjwetXH+PjCd+YFT4L7qcR1y7eVDdg==,iv:j/Rk0y/onogzX4a/7UbjuiJY8Sx3PjxJZhDxC40uBR8=,tag:8b9pl1EyTB8J69h2NEqASQ==,type:str]
radicale:
    htpasswd: ENC[AES256_GCM,data:7TWKFq+GpaU7lLSh+2cBC+wALAIDa/wxzoX/EMdS+lQtV8qlALHB,iv:xIr5PRqya06ukxyUDhzEcx4V0UWTvBtDmnUmZdyXisI=,tag:TLQQjw7LKJmXGZjxPDM/ZA==,type:str]
sops:
    age:
        - recipient: age1r7u3v4csrvqqcxw0u0mgz22qa63ft3sscdl8yan2ge4k7trtacjqy0w7uf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc3dYbHllY3A3VE9tY3M0
            L29DZzVZcmhSbHRaNE5obWdzUWtjWU9zYVJjCmQrT09QMkd5YmRtbDcyOGRFbVA0
            UERNWTEzMTlwbC9jU0FvYTB3Vmx6eTgKLS0tIGIyODdwMlMxcXZ1SmF6dlBxNTRi
            d3pNM0s2UlFwaW9wM3k4V1pCOXhTeWsKjT+yx4t4kMEGgMJe+xWtv/YQksc6fN3R
            IEJ2S3aksn9iWQRqnovf+9ez25MGvJMk+gFHmLA35e8QYKPYPxajwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ate9csmpldp5596mkfs4lklj9338ahgqd2lxtv757wp8xey75mq9e5gvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTenYwai9JVUo4RWZqY3dY
            OERnK0lnOW9uUzBHeXpGaE1yL1FRSVJpUWlFCndyYUU0RHZVL1pYV1NRRHZ1RTFI
            c1hzcHlCcmFOYWdFekp0Rm55aXlkcE0KLS0tIEh4SFVjSmpFOHFOQ0d3VGUxU3dX
            ZUxwMVkvR1k2OXp0R3M1TEw0aWdGeTQKvzD3rLsGZAQxE5xc/6lJkawqQ0Lf9gKC
            UX7TA8fNi0mvtHmoEWCURa/GdLbmHXMg7eMq/Y2MpUsYHkM3RL2YqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T07:00:06Z"
    mac: ENC[AES256_GCM,data:8ZRp0Lvbpece72TzTsl+GWjQYL3HKNtuqDWE7vBNYgYFyR/FSVpazfiGnEfRTLUFrDTWluIRTz5pRaZd/RzsAZS0eXIVw36ArepaM4Kfw2lOVhC81GYF4uA/Z98j4Fr+rSw0COFqnHoK1xlHR1yXaG8692Cd3i+xWrmXj1fS5oA=,iv:cu2FwLgAZozc8M20mYU/LwbY2kHhV959vxC6yoci6yM=,tag:V7fuaJ8EQ9ZPSjxSIeyCHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
